/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_chr1s_threading_Thread */

#ifndef _Included_io_chr1s_threading_Thread
#define _Included_io_chr1s_threading_Thread
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_chr1s_threading_Thread
 * Method:    start0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_chr1s_threading_Thread_start0
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
